### ISSUE TITLE
Feature Request: Allow settings to be changed right from Sketch

### ISSUE THREAD

**Issue by ryanbelisle** [timothywhalin/Sketch-Quick-Presentation#1]
@timothywhalin Thanks for this slick plugin! Love using it to quickly send off different design variations.

I have a feature suggestion if you're open to it? How about allowing all of the settings to be changed via the Sketch interface vs. having to modify the plugin manually?

**Comment by timothywhalin** [comment]
I love that idea and agree it would be helpful. I'll look into how to add that. :)

**Comment by timothywhalin** [comment]
I just added a new Settings menu item. Great idea and thank you for the suggestion. Please let me know if you find anything else that could make the plugin easier to use.
