### ISSUE TITLE
Exported in Sketch 49, artboard is blank.

### ISSUE THREAD

**Issue by hanuse** [timothywhalin/Sketch-Quick-Presentation#12]
Hi,
Exported in Sketch 49, artboard is blank.
Please fix it，thanks!

**Comment by prodocik** [comment]
Same issue, please fix it.

**Comment by timothywhalin** [comment]
In Sketch 49, they no longer allow wrapping an Artboard around another Artboard. The only alternative is using a slice to export. I have updated the plugin to v1.5 that replicates the previous behavior, but with a slice. Please try it out and let me know if you have any issues with it.

Thanks!
Tim
