### ISSUE TITLE
The shadow is always set up as 0 opacity.

### ISSUE THREAD

**Issue by donbailon** [timothywhalin/Sketch-Quick-Presentation#4]
If you export with shadows, the shadows opacity is always 0. :(

**Comment by timothywhalin** [comment]
The shadow can only be set to 0 to 1. 0.25 would be 25% opacity. What is your value of the shadow opacity set to? I just confirmed this is working so I'm guessing there is a wrong value set in that input.

**Comment by donbailon** [comment]
Oh mate, In my mac the default shadow is 0,2 and it was not working... if I change the default shadow to 0.2 it works. Thanks. 

Good plugin and  very useful.
