### ISSUE TITLE
Can't Use Plugin In Sketch 44 :[

### ISSUE THREAD

**Issue by honeyhorny** [timothywhalin/Sketch-Quick-Presentation#8]
Can't Use Plugin In Sketch 44 :[

**Comment by timothywhalin** [comment]
The plugin is working for me in 44.1. Can you double check you have the latest and let me know if its still not working?

**Comment by timothywhalin** [comment]
The plugin is working for me with Sketch 44.1. Please make sure to download and use the latest version as I had to fix a bug with Sketch 43 that made the plugin no longer work.
